title: Vaclav SISL - data, energy, sustainability
description: data-centric software development, energy and sustainability consulting
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman